# Generated by Django 5.0.14 on 2026-09-07 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequest',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='field_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='lab_measurements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='lab_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='sample_category',
            field=models.CharField(choices=[('riverbed_soil', 'Riverbed Soil'), ('sediment', 'Sediment'), ('water', 'Water Quality'), ('concrete_block', 'Concrete / Construction Material'), ('geotextile', 'Geotextile'), ('other', 'Other')], default='riverbed_soil', max_length=50),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='sample_tag_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='sampling_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SampleCustodyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('collected_field', 'Collected in Field'), ('received_reception', 'Received at Lab Reception'), ('delivered_lab', 'Delivered to Specialized Lab'), ('in_testing', 'Testing in Progress'), ('storage', 'Moved to Sample Storage'), ('completed', 'Testing Completed & Archived')], default='received_reception', max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('custody_notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('test_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_logs', to='tests.testrequest')),
                ('transferred_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_transfers_from', to=settings.AUTH_USER_MODEL)),
                ('transferred_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_transfers_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sample_custody_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TestCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('verification_code', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('digital_signature_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('test_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='tests.testrequest')),
            ],
            options={
                'db_table': 'test_certificates',
                'ordering': ['-issued_at'],
            },
        ),
    ]
