# Generated by Django 5.0.14 on 2026-09-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('officer', 'Officer'), ('lab_technician', 'Lab Technician'), ('field_inspector', 'Field Inspector'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
